### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by bsl-zcs** [plutext/docx4j#38]
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] \Temp\4\docx4j\src\main\java\org\docx4j\convert\out\AbstractTableWriter.java:[50,43] error: cannot find symbol
[ERROR] \Temp\4\docx4j\src\main\java\org\docx4j\convert\out\AbstractTableWriter.java:[343,22] error: cannot find symbol
```

Probably, caused by changes introduced in commit 5f52ecd8873e6c319b7c311229947b26b7037383 

PS. I’m fairly new to all that github thing, just registered to send one pull request.  Now I’m trying to ensure it builds on master branch.  My changes 05fdacbc077803bd9f252d3918ea713edcb99dc6 are quite trivial, maybe I should send my request regardless of current build status?
